# This file is managed by FlowCrafter. Manual changes will be overwritten
# the next time you run FlowCrafter.
---
library:
  github:
    owner: jdno
    repository: workflows
workflows:
  - name: github
    jobs:
      - sync-labels
