---
repository:
  name: otterplaces
  description: 🗺️ What are otter places that you want to see?

  # The app is developed as closed-source for now.
  private: false

  default_branch: main

  # Only allow squash commits to maintain a clean commit history.
  allow_squash_merge: true
  allow_merge_commit: false
  allow_rebase_merge: false

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
        require_code_owner_reviews: true
        dismiss_stale_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: false
        contexts:
          - "Check style"
          - "Lint code"
      enforce_admins: true
      required_linear_history: true
      restrictions: null

labels:
  - name: C-bug
    color: e74c3c
    description: "Report a new bug"
  - name: C-dependency
    color: e74c3c
    description: "Change or update a dependency"
  - name: C-documentation
    color: e74c3c
    description: "Improve the documentation"
  - name: C-feature-request
    color: e74c3c
    description: "Request a new feature"
  - name: L-github
    color: 34495e
    description: "Tag the GitHub ecosystem"
  - name: L-node
    color: 34495e
    description: "Tag the Node ecosystem"
  - name: PR-block
    color: 3498db
    description: "Do not merge the pull request"
  - name: PR-merge
    color: 3498db
    description: "Merge pull request when checks passed"
  - name: R-added
    color: 95a5a6
    description: "Add a new feature to the release notes"
  - name: R-changed
    color: 95a5a6
    description: "Add a change in existing functionality to the release notes"
  - name: R-deprecated
    color: 95a5a6
    description: "Add a soon-to-be removed feature to the release notes"
  - name: R-fixed
    color: 95a5a6
    description: "Add a fixed bug to the release notes"
  - name: R-ignore
    color: 95a5a6
    description: "Do not add this pull request to the release notes"
  - name: R-removed
    color: 95a5a6
    description: "Add a now removed feature to the release notes"
  - name: R-security
    color: 95a5a6
    description: "Add a vulnerability warning to the release notes"
