[toolchain]
channel = "stable"
components = [
    "clippy",
    "rustfmt",
]
targets = [
    "aarch64-apple-darwin",
    "aarch64-apple-ios",
    "aarch64-apple-ios-sim",
    "x86_64-apple-darwin",
]
