---
name: YAML

"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  detect-changes:
    name: Detect changes
    runs-on: ubuntu-latest

    outputs:
      any_changed: ${{ steps.detect-changes.outputs.any_changed }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get changed files
        id: detect-changes
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.yaml
            **/*.yml
            .github/workflows/yaml.yml

      - name: Print changed files
        run: |
          for file in ${{ steps.detect-changes.outputs.all_changed_files }}; do
            echo "$file"
          done

  lint:
    name: Lint YAML files
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run yamllint
        uses: actionshub/yamllint@v1.8.2

  style:
    name: Check YAML style
    runs-on: ubuntu-latest

    needs: detect-changes
    if: needs.detect-changes.outputs.any_changed == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Prettier
        run: npx prettier --check "**/*.{yaml,yml}"
